export const NOTIFICATIONS = [
    {
        type: 'teacher',
        id: '1',
        name: 'Nguyen Quang Hai',
        school: 'THPT Phan Boi Chau',
        date: new Date(2019, 4, 1, 15, 24),
        avatar: './public/assets/img/avatars/1.jpg',
    },
    {
        type: 'student',
        id: '2',
        name: 'Park Hang Seo',
        school: 'THCS Le Quy Don',
        date: new Date(2019, 3, 30, 20, 47),
        avatar: './public/assets/img/avatars/2.jpg',
    },
    {
        type: 'student',
        id: '3',
        name: 'Phan Van Duc',
        school: 'THCS Tran Binh Trong',
        date: new Date(2019, 3, 30, 18, 33),
        avatar: './public/assets/img/avatars/3.jpg',
    },
    {
        type: 'student',
        id: '4',
        name: 'Nguyen Cong Phuong',
        school: 'TH Nguyen Thai Binh',
        date: new Date(2019, 3, 30, 8, 19),
        avatar: './public/assets/img/avatars/4.jpg',
    },
    {
        type: 'teacher',
        id: '5',
        name: 'Le Cong Vinh',
        school: 'THPT Le Hong Phong',
        date: new Date(2019, 3, 28, 22, 1),
        avatar: './public/assets/img/avatars/5.jpg',
    },
    {
        type: 'student',
        id: '6',
        name: 'Vu Dao Anh Tuan',
        school: 'THPT Nguyen Binh Khiem',
        date: new Date(2019, 3, 27, 1, 59),
        avatar: './public/assets/img/avatars/6.jpg',
    },
    {
        type: 'teacher',
        id: '7',
        name: 'Luong Tuan Kiet',
        school: 'THPT Ngo Gia Tu',
        date: new Date(2019, 2, 12, 23, 0),
        avatar: './public/assets/img/avatars/7.jpg',
    },
];